export const authTypes={
  LOGIN_REQUEST:"LOGIN_REQUEST",
  LOGIN_SUCCESS:"LOGIN_SUCCESS",
  LOGIN_FAILED:"LOGIN_FAILED",
  LOGOUT_REQUEST:"LOGOUT_REQUEST"

}
export const searchTypes={
  SEARCH_REQUEST:"SEARCH_REQUEST",
  SEARCH_SUCCESS:"SEARCH_SUCCESS",
  SEARCH_FAILED:"SEARCH_FAILED",
  SEARCH_COMPLETE:"SEARCH_COMPLETE"
}
export const selectChatTypes={
  ACCESS_REQUEST:"ACCESS_REQUEST",
  ACCESS_SUCCESS:"ACCESS_SUCCESS",
  ACCESS_FINISHED:"ACCESS_FINISHED",
  ACCESS_FAILED:"ACCESS_FAILED"
}
export const chatsTypes={
  CHAT_REQUEST:"CHAT_REQUEST",
  CHAT_SUCCESS:"CHAT_SUCCESS",
  CHAT_FAILED:"CHAT_FAILED",
  CHAT_ADD:"CHAT_ADD",
  CHAT_INIT:"CHAT_INIT",
  CHAT_GROUP_RENAME:"CHAT_GROUP_RENAME",
  CHAT_MEMBER_UPDATE:"CHAT_MEMBER_UPDATE",
  CHAT_DELETE:"CHAT_GROUP_DELETE"
}

export const MembersRequestTypes={
  MEMBER_REQUEST:"MEMBER_REQUEST",
  MEMBER_SUCCESS:"MEMBER_SUCCESS",
  MEMBER_FAILED:"MEMBER_FAILED",
  SEARCH_INIT:"SEARCH_INIT"
}

export const ChatGroupTypes={
  GROUP_RENAME_REQUEST:"GROUP_RENAME_REQUEST",
  GROUP_RENAME_SUCCESS:"GROUP_RENAME_SUCCESS",
  GROUP_RENAME_ERROR:"GROUP_RENAME_ERROR",
  GROUP_RENAME_INIT:"GROUP_RENAME_INIT",

  ADD_MEMBER_REQUEST:"ADD_MEMBER_REQUEST",
  ADD_MEMBER_SUCCESS:"ADD_MEMBER_SUCCESS",
  ADD_MEMBER_ERROR:"ADD_MEMBER_ERROR",
  ADD_MEMBER_INIT:"ADD_MEMBER_INIT",

  DROP_MEMBER_REQUEST:"DROP_MEMBER_REQUEST",
  DROP_MEMBER_SUCCESS:"DROP_MEMBER_SUCCESS",
  DROP_MEMBER_ERROR:"D,ROP_MEMBER_ERROR",
  DROP_MEMBER_INIT:"DROP_MEMBER_INIT"
}

export const messageTypes={
  ALL_MESSAGE_REQUEST:"ALL_MESSAGE_REQUEST",
  ALL_MESSAGE_SUCCESS:"ALL_MESSAGE_SUCCESS",
  ALL_MESSAGE_ERROR:"ALL_MESSAGE_ERROR",
  ALL_MESSAGE_DESTROY:"ALL_MESSAGE_DESTROY",
  ADD_NEW_MESSAGE_REQUEST:"ADD_NEW_MESSAGE_REQUEST",
  ADD_NEW_MESSAGE_SUCCESS:"ADD_NEW_MESSAGE_SUCCESS",
  ADD_NEW_MESSAGE_ERROR:"ADD_NEW_MESSAGE_ERROR"
}

export const notificationTypes={
  NOTIFY_SUCCESS:"NOTIFY_SUCCESS",
  NOTIFY_RESET:"NOTIFY_RESET"
}
